### ISSUE TITLE
Side content fails to correctly update active tab in Redux store

### ISSUE THREAD

**Issue by Aulud** [source-academy/cadet-frontend#1369]
## [Bug] Side content fails to correctly update active tab in Redux store
Major bug.

### Bug description
After the refactor of `SideContent` to support dynamic tabs in PR #1352, the value of the selected tab of the current workspace (`sideContentActiveTab` prop) in the Redux store is no longer correctly updated whenever the selected tab is changed by the user.

This breaks the run-all functionality of the Autograder when it is the currently selected tab, since this is executed via a condition in the saga for `EVAL_EDITOR` which checks that the value of the selected tab of the current workspace is `SideContentTypes.Autograder`. This can be verified by logging the value of the side content tab observed in the saga below (see `activeTab` in the relevant code section below).

https://github.com/source-academy/cadet-frontend/blob/8f617f50885e1f282f7ede6a9fc2379372614c58/src/commons/sagas/WorkspaceSaga.ts#L710-L716

### Replication instructions
1. Navigate to any assessment or submission, then proceed to any **programming** (not MCQ) question
2. Bring up the side-content Autograder (airplane icon), and evaluate the editor's contents, and verify that none of the testcases are run

Last updated 18 Jul 2020, 11:45PM

**Comment by bnjmnt4n** [comment]
I believe this bug still exists in a more subtle form: when navigating from 1 page in an assessment to another (not sure if I got the terminology right), if I'm on the test cases tab in the first page, upon navigation to the second page the test cases tab will still be shown, but the expected behaviour of clicking run to evaluate test cases will not work. Only after manually switching tabs back and forth to test cases again would this work.

I'm guessing the easiest way to fix this might be to update https://github.com/source-academy/cadet-frontend/blob/5bf07b67b3dac4676a99a9c95657c6698523e353/src/commons/sideContent/SideContent.tsx#L60-L64 to either reset the tab to the default tab on page change or set it to the same tab as before, although I'm not too sure how the redux store is structured to make it do so on page change.
