### ISSUE TITLE
Bug - 2.3.4 - Expected string or number on left hand side of operation, got array.

### ISSUE THREAD

**Issue by htdat** [source-academy/cadet-frontend#1451]
### Steps to replicate the issue 

From https://source-academy.github.io/sicp/chapters/2.3.4.html#h2

I clicked this link https://share.sourceacademy.nus.edu.sg/4g to test the `weight` function. But the same errors happen for the `symbols` function. 

I expected to get `11`. However, this is what I guess: 

![Screen Shot on 2020-08-09 at 21:25:52](https://user-images.githubusercontent.com/10045087/89734561-022a7b00-da87-11ea-874e-51ae324f91ba.png)

Errors:

```
Line 7: Expected string or number on left hand side of operation, got array.
Hints:
Line 36: A type mismatch was detected in the function call:
  weight_leaf(tr ... ee)
The function expected an argument of type:
  [T0, [T1, [T2, T3]]]
but instead received an argument of type:
  [string, [T0, [List<T1>, T2]]]
``` 

### Workaround

If I choose `Source §3`, it works correctly. However, I am not sure it affects anything then. 

![Screen Shot on 2020-08-09 at 21:29:06](https://user-images.githubusercontent.com/10045087/89734625-7533f180-da87-11ea-86f4-14f7837820d7.png)

### Solution 

I am not familiar with how this really works behind. But my humble guess is that there are something missing in the sublanguage ` Source §2`.

**Comment by martin-henz** [comment]
This is already a problem in the original SICP (Scheme). The primitive function eq? is introduced in 2.3.1 as an operation on symbols (SICP JS uses strings to represent symbols), but the function leaf? (is_leaf) applies eq? to the first element of a code tree, which is a list. The problem shows up due to the recent restriction of === to strings and numbers. The fix is to give code trees a tag, like leaves. The fix is already installed in SICP JS, so you can run the example again and see that it works as expected.

**Comment by htdat** [comment]
Thank you. I confirm it's working now!
