### ISSUE TITLE
Display performance is slow

### ISSUE THREAD

**Issue by blackening** [source-academy/cadet-frontend#1494]
![image](https://user-images.githubusercontent.com/1753927/91792052-2d982400-ec47-11ea-8f10-983097870a9b.png)

Please note, this depends on computer / browser / luck when running. I haven't rebooted my computer for some time so it's slower than usual. However, it's not THAT slow.

**Comment by martin-henz** [comment]
similar to 
https://github.com/source-academy/js-slang/issues/371

**Comment by thomastanck** [comment]
The particular benchmark mentioned in the screenshot should not be js-slang's fault, as `display`ing a single number should still take a really short amount of time on the js-slang end.

I looked into it and this is what gets called for every display call in cadet-frontend

https://github.com/source-academy/cadet-frontend/blob/d0fb4e6e87f4ec6e08f7d0055d4a6a338c8e7e45/src/commons/utils/JsSlangHelper.ts#L46-L53

It's possible that display is slow in this benchmark not because js-slang is slow but because of the overhead incurred by redux. Since there's a "TODO in 2019: fix this hack" in there anyway, I think this might need additional investigation by someone from the frontend team.

**Comment by thomastanck** [comment]
Just tested by disabling the "fix this hack" code, and I can run 10k iterations with no issue.

![image](https://user-images.githubusercontent.com/829070/118275309-d8f8b880-b4f8-11eb-8e40-16c573004cf4.png)

![image](https://user-images.githubusercontent.com/829070/118275375-eca41f00-b4f8-11eb-8304-0112b85fd1c8.png)

So the bad performance of display in this benchmark is likely contributed by cadet-frontend. Reopening.

**Comment by blackening** [comment]
My intuition is that react is trying to re-render the entire page every time we put something in there asynchronously.

**Comment by martin-henz** [comment]
Ah, @thomastanck sorry for barking up the wrong tree.

**Comment by martin-henz** [comment]
> My intuition is that react is trying to re-render the entire page every time we put something in there asynchronously.

I see. Sounds fixable.

**Comment by blackening** [comment]
![image](https://user-images.githubusercontent.com/1753927/120105899-63921680-c18d-11eb-8ec6-3246a305acec.png)

Much better :D
