### ISSUE TITLE
[Feature Request] VSCode extension for Source Lang

### ISSUE THREAD

**Issue by rish-16** [source-academy/cadet-frontend#1505]
It'd be nice to have a VSCode extension for Source programs. I've realised that sometimes, on campus, wifi isn't that strong – so it's almost impossible to load the sourceacademy.nus.edu.sg website fully. 

Right now, the only way to access Source is through the web playground. Is it possible to have a VSC extension for Source lang and a terminal/cmd prompt interpreter? This way, we can practice with Source offline as well. Also, with a VSC extension, it might be a change of colour theme aside from the familiar web app theme.

**Comment by angelsl** [comment]
It's kind of hard to have a fully-featured terminal interpreter because of runes/curves/sounds&mdash;can't trivially display those in a terminal, though you could come up with a solution if you had enough time.

But there is a CLI REPL available (just without the frontend-specific RUNES/etc libraries); it's in js-slang. See the README there for instructions.

**Comment by rish-16** [comment]
Oh cool thanks
