### ISSUE TITLE
Organise miscellaneous properties under state/workspaces

### ISSUE THREAD

**Issue by remo5000** [source-academy/cadet-frontend#161]
Having 4 properties loosely places is going to become confusing. Better to store them together. What do you think @ningyuansg ?
e.g 
```
Misc
  currentAssessmentId
  currentQuestionId
  currentSubmissionId
  gradingComments
```

**Comment by ningyuansg** [comment]
I'm planning on implementing a logout button soon after the user controller is implemented at backend [#89](https://github.com/source-academy/cadet/pull/89). 

- It makes sense to me that the logout saga action should nuke the `session` slice of the state
- In that case, everything we want to be nuked should be stored in the session, so that we don't need to nuke many things
- These properties seem to be something we want to nuke on logout
- So probably place them in `session`

**Comment by remo5000** [comment]
Actually, I think we should nuke 
- Everything in the state, and make it the `defaultState`
- The localStorage, so that one does not have a token to login with

If not, we would need to nuke the workspaces as well, and in general place a lot of things inside the `ISessionState`. Is there anything that must be preserved when logging out?

**Comment by ningyuansg** [comment]
We should preserve the playground state (if logging in does not change this, neither should logging out), and eventually the news and material as well.

**Comment by remo5000** [comment]
Solved after using inheritance for `IWorkspaceState`, and playground code has been saved.
