### ISSUE TITLE
Blocking assessments?

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#201]
Is it possible to make some assessments "blocking", i.e. preventing access to future assessments?

An example of this could be Paths. A Path that follows a lecture could block a corresponding Mission.

**Comment by remo5000** [comment]
Good idea Prof @martin-henz . With respect to most features regarding access, we let the backend handle wether the information should be provided. In this case, a Path could be given an opening time that is right after the lecture so that it appears only after the lecture (already implemented). Or is the intention to display Assessments that are going to be available *soon*, but not just yet? (potential new feature)

An example is that a student can see a Path being "blocked" before the lecture, allowing them to know that there is a path regarding the lecture (that is likely to open up after the lecture ends).

**Comment by martin-henz** [comment]
A little misunderstanding, regarding my example. More concretely: Lecture L2 is on 22/8, and Path P2A opens right after the lecture. Mission M2A also opens on 22/8 after the lecture. If we would have "blocking" assessments as I'm suggesting, we could arrange M2A to open for a particular student only after she has completed P2A. This would allow us to _force_ students to complete paths without "spending" any grades on them.

**Comment by ningyuansg** [comment]
I think the backend team will be able to better discuss this. The reason being that implementing this feature on the frontend is in most cases rather trivial (but not instantaneous), dealing only with filtering results fetched from the backend. Most of the solutions I can imagine right now require a change in the way that the backend represents an assessment.

**Comment by ningyuansg** [comment]
Moved to https://github.com/source-academy/cadet/issues/126.
