### ISSUE TITLE
null crashes REPL in playground

### ISSUE THREAD

**Issue by jkli123** [source-academy/cadet-frontend#307]
typing in null; into the playground interpreter produces a typeerror: "e is null"

**Comment by ningyuansg** [comment]
Thanks for bringing this up! Will fix in #304. For more information, see also https://github.com/source-academy/js-slang/issues/30.

**Comment by ningyuansg** [comment]
Does the source program `null;` crash the REPL, or does it produce a TypeError? I don't think both of these things can happen together. Either way, will fix the former with #304, see https://github.com/source-academy/js-slang/issues/30 for more info. W.r.t. the latter, it is intended behaviour, since `null` is not specified in our source language.
