### ISSUE TITLE
About, Team, Help pages

### ISSUE THREAD

**Issue by rrtheonlyone** [source-academy/cadet-frontend#609]
Now that we have grown as a team, it is important to recognise the efforts that all of us have put in.

We should work on an improved contributors page listing our teams' contributions for all our various projects (Github allows for this information to be retrieved). Any suggestions for this page can be put in this issue as well!

**Comment by martin-henz** [comment]
I suggest that we change the DOWN button on the top right as follows:
* About: 

The Source Academy is an experimental environment for learning programming in the CS1101S module at the National University of Singapore.

This iteration of Source Academy, code-named Cadet, is available under the MIT License. You may find the source code for Cadet at our GitHub organisation, Source Academy.

* Team:

One page with the following:

Leadership
Backend: 
Frontend Team

Lee Ning Yuan • Vignesh Shankar • Rahul Rajesh

Backend Team
 • Liow Jia Chen

Source Team

Tan Chee Kun, Thomas

Hall of Fame:

Ng Tse Pei • Joey Yeo • Tan Yu Wei





* Help: similar to what we have

**Comment by geshuming** [comment]
Looks good

**Comment by sandydays** [comment]
From what I can see, there are two overarching issues we need to tackle:

1. How should a user be able to navigate to the Contributors page? The route to the contributors page via /contributors has been created, but where should a user to click to reach this page? We want to make it prominent. But there are few issues with how we are going to go about doing that:

a) Dropdown > About > Developers tab > 'here' word that when clicked links to the contributors page --> this is what I had implemented previously, but we don't know whether it would be prominent enough.

b) Another idea I had was very similar to what Prof Matrin has mentioned: adding a Team menu item under the dropdown, but this might be inconsistent since all the menu items when clicked lead to pop up but when Team is clicked it will take the user to a completely new page.

However, Prof, you have mentioned that clicking Team still takes us to a popup page with a brief overview of the leadership, hall of fame, etc. and then we have all contributors listed. This would solve the issue of any inconsistencies. However, to clarify, are All Contributors to be rendered in that popup or is there is a link that takes the user to a separate page where all contributors would be shown? 

Showing everything in the popup could get messy unless we show just the top contributors and then link the rest to another page. On the other hand, if we are not showing the contributors in the popup and just linking to another page, we need to consider whether this is prominent enough (I think it should be okay though). 

c) Another idea is to put it out as a button in the main navbar, but I feel that is not the right place for it to be in thematically. 

2. The second problem that we need to consider is what should the Contributors page itself contain? Currently I added some dummy text and html for a section titled Special thanks to anyone who has majorly contributed in the past to the Source Academy (very similar to Hall of Fame as Prof Martin put in his comment), and a section for the Developers that was previously under Dropdown> About. If we go by Prof Martin's suggestion, to stick with keeping them within the popup, then there is no need for them to be within the Contributors Page, and I think that works too and keeps things more clean.

Let us discuss these and reach a consensus on the organization of the page!

**Comment by martin-henz** [comment]
Sandy says:
**However, to clarify, are All Contributors to be rendered in that popup or is there is a link that takes the user to a separate page where all contributors would be shown?.**

I suggest that we render all contributors in that popup. It can be scrolled, right? In addition, we should have a link to a separate page with the same info. That link will serve as a permalink.

**Comment by martin-henz** [comment]
This is handle by: https://github.com/source-academy/cadet-frontend/pull/612

**Comment by martin-henz** [comment]
Original PR is merged, with a new PR that is well under way.
